name: EXE Build

on:
  workflow_run:
    workflows: ["Java Build"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download JAR artifact
      uses: actions/download-release-asset@v1
      with:
        tag: v1.0.0
        asset_name: resume-builder-1.0-SNAPSHOT.jar

    - name: Download and Extract Launch4j
      run: |
        wget https://sourceforge.net/projects/launch4j/files/launch4j-3/3.14/launch4j-3.14-linux.tar.gz
        tar -xzf launch4j-3.14-linux.tar.gz

    - name: Convert JAR to EXE
      run: |
        ./launch4j/launch4j launch4j-config.xml

    - name: Upload EXE artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/resume-builder.exe
        asset_name: resume-builder.exe
        asset_content_type: application/octet-stream
